version: '3'

services:
  app:
    image: heyui:1.0
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./.env.docker:/app/.env
      - ./key-pair:/app/key-pair
      - ./certs:/app/certs
  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=ui_test
      - APP_DB_PASS=ui_test
      - APP_DB_NAME=ui_test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  envoy:
    image: envoyproxy/envoy:v1.21.1
    ports:
      - "9901:9901"
      - "8443:8443"
    restart: always
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./certs:/etc/envoy/certs

  prometheus:
    image: prom/prometheus:v2.34.0
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.4
    ports:
      - "3000:3000"
    restart: always